# Generated by Django 4.0 on 2021-12-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_to_offer', models.URLField(max_length=400)),
                ('offered_nepenthes', models.CharField(max_length=100)),
                ('rating', models.CharField(choices=[('1', 'positive'), ('0', 'neutral'), ('-1', 'negative')], default='1', max_length=2)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nepenthes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('inflorescence', models.CharField(choices=[('0', 'no flower '), ('1', 'flowering in development'), ('2', 'flower')], default='0', max_length=2)),
                ('image', models.FileField(upload_to='images')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
