# Generated by Django 4.0 on 2021-12-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollen_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='buyer',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='seller',
            field=models.CharField(default='rs', max_length=50),
            preserve_default=False,
        ),
    ]
