# Generated by Django 4.0 on 2022-01-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollen_app', '0002_feedback_buyer_feedback_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='nepenthes',
            name='eu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nepenthes',
            name='owner',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nepenthes',
            name='sex',
            field=models.CharField(choices=[('0', 'male '), ('1', 'female')], default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='nepenthes',
            name='usa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nepenthes',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
