# Generated by Django 3.2.12 on 2022-02-01 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pollen_app', '0003_nepenthes_eu_nepenthes_owner_nepenthes_sex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nepenthes',
            name='eu',
        ),
        migrations.RemoveField(
            model_name='nepenthes',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='nepenthes',
            name='usa',
        ),
        migrations.AlterField(
            model_name='nepenthes',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='nepenthes',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
